require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '13.0'

$FirebaseSDKVersion = '7.7.0'

target 'TikTokClone' do
  pod 'react-native-ffmpeg/https-gpl', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'TikTokCloneTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

end

target 'TikTokClone-tvOS' do
  # Pods for TikTokClone-tvOS

  target 'TikTokClone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
